### PR TITLE
fix issue: #1 build failed

### PR DESCRIPTION
**Pull request by pcloves**
try to fix compile errors.

### CODE REVIEW

**Comment by pcloves** [comment]
There is also a runtime error, even though all the compile errors are fixed.

image

**Comment by pcloves** [comment]
> There is also a runtime error, even though all the compile errors are fixed.
> 
> image

I have pulled a [PR](https://github.com/AnomalousUnderdog/ldtkimport/pull/1) to try to fix this runtime issue.

**Comment by AnomalousUnderdog** [comment]
Sorry about that, will take a look at this when I get the time over the weekend.

**Comment by AnomalousUnderdog** [comment]
Fix implemented 8ef619d3feecfb6e010622e7443c336ebe6916d8

**Pull request closed without merging**
